### ISSUE TITLE
与 FoF Formatting 插件不再兼容

### ISSUE THREAD

**Issue by acolasialiuliu** [tohsakrat/fancybox-plus#2]
![图片](https://github.com/tohsakrat/fancybox-plus/assets/62091678/2a983e6d-9914-45be-827c-3adab42739de)
一个整理格式的插件，紧挨着的图可以一起排列，上个版本还能行来着哈哈哈哈

**Comment by LiuFenCN** [comment]
![图片](https://github.com/tohsakrat/fancybox-plus/assets/62091678/def95e82-ecd5-4168-91c2-ad2915f672b7)
xian在我开启了原先的灯箱，欢迎随时查看 https://bbs.cathi.cn/d/143-tu-pian-fa-bu-ce-shi/4

**Comment by tohsakrat** [comment]
虽然但是我的插件是fancybox-plus，绿色的那个才是我的
你打开的是原版fancybox

**Comment by LiuFenCN** [comment]
对，因为你那个不兼容了，所以我换回去了，不然这几张图片一大堆往下排列

**Comment by LiuFenCN** [comment]
我现在打开给你看

**Comment by tohsakrat** [comment]
你这个箱子也不是fof formatting的效果吧，像是Post Galleries
你只是需要纯样式，与其用插件，不如直接用css写。
粘贴到后台-外观-自定义css，然后提交就可以
上面的4是图片的高度，下面的0.5是图片之间的距离，根据需要改


a[data-fancybox]>img {
    max-height: 4em!important;
}

.Post-body a[data-fancybox] {
    display: inline-block!important;
    margin-left: 0.5em!important;
}

![image](https://github.com/tohsakrat/fancybox-plus/assets/45536831/a95dcfc3-7c85-4bba-a091-10db9f61a0a2)

**Comment by LiuFenCN** [comment]
牛，具体我不清楚，上面那张图就是之前版本和fof formatting的效果，刚玩这个，就在社区找来找去哈哈哈，感谢
